"""derniera

Revision ID: 0069dd0ff393
Revises: 74695147877a
Create Date: 2022-10-19 14:17:30.705527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0069dd0ff393'
down_revision = '74695147877a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('utilisateur', sa.Column('dernier_acces', sa.DateTime(), nullable=True))
    #op.drop_column('utilisateur', 'mot_de_passe')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('mot_de_passe', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('utilisateur', 'dernier_acces')
    # ### end Alembic commands ###
