"""mise a jour mdp

Revision ID: 43d15f887efa
Revises: a50dbca31dfc
Create Date: 2022-09-12 16:13:08.042756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d15f887efa'
down_revision = 'a50dbca31dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('mot_de_passe', sa.String(length=128), nullable=True))
    op.drop_column('utilisateur', 'mot_de_passe_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('mot_de_passe_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('utilisateur', 'mot_de_passe')
    # ### end Alembic commands ###
