"""a propos

Revision ID: 65c60cdcdc72
Revises: 7bf2c3b6478b
Create Date: 2022-09-12 14:34:15.796198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c60cdcdc72'
down_revision = '7bf2c3b6478b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('a_propos_de_moi', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'a_propos_de_moi')
    # ### end Alembic commands ###
