"""partisans

Revision ID: 908d90f98a02
Revises: 0069dd0ff393
Create Date: 2022-10-21 13:04:12.905377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908d90f98a02'
down_revision = '0069dd0ff393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partisans',
    sa.Column('partisan_id', sa.Integer(), nullable=True),
    sa.Column('utilisateur_qui_est_suivi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partisan_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_qui_est_suivi_id'], ['utilisateur.id'], )
    )
    op.drop_column('utilisateur', 'mot_de_passe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('mot_de_passe', sa.VARCHAR(length=128), nullable=True))
    op.drop_table('partisans')
    # ### end Alembic commands ###
