"""a propos

Revision ID: a50dbca31dfc
Revises: 65c60cdcdc72
Create Date: 2022-09-12 14:38:29.360460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50dbca31dfc'
down_revision = '65c60cdcdc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('avatar', sa.Text(length=131072), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'avatar')
    # ### end Alembic commands ###
